name: CMakeBuild

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  unbuntu_build:
    name: ubuntu-18.04
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: sudo apt-get install libsdl2-dev && sudo apt-get install libsdl2-image-dev
    - name: Run cmake
      run: cmake .
    - name: Run cmake release build
      run: cmake --build . --config Release --target all
